language: ruby
# We're stuck on old bundler to verify 1.8 builds.
before_script:
 - rvm @global do gem uninstall bundler -ax
 - gem install bundler -v 1.3.5
rvm:
 - 1.8.7
 - 1.9.2
 - 1.9.3
 - 2.0.0
 - jruby-18mode
 - jruby-19mode
 - rbx
cache: bundler
